### ISSUE TITLE
Migration from Vanilla Ender Chest Not Functioning.

### ISSUE THREAD

**Issue by ghost** [minion325/BetterEnderChests#9]
I'm using purpur 1.20.4.
Even with "convert-current-ender-chest: false", migration from the vanilla ender chest doesn't work.

**Comment by minion325** [comment]
Send a screenshot of your enderchest when you open it.

**Comment by ghost** [comment]
You placed a golden apple in the ender chest.
After enabling the plugin, when you checked the ender chest, the golden apple was not migrated and is missing.
![スクリーンショット (95)](https://github.com/minion325/VariableEnderChests/assets/101532725/79e5bd43-c56f-4356-afb7-6f8e877134a0)
![スクリーンショット (101)](https://github.com/minion325/VariableEnderChests/assets/101532725/141ac8f8-9e4c-42dc-98fc-e9ccc40386b8)

**Comment by minion325** [comment]
How the plugin migrates ender chests is like this:

1. Plugin enabled for first time ever
2. Player 1 joins server
3. Contents of Player 1's vanilla ender chest are copied over to
VariableEnderChests
4. Anytime Player 1 rejoins the server, the VariableEnderChests chest is
loaded instead of the vanilla one.

What I suppose may have happened here is that you loaded up the plugin,
joined the server woth an empty enderchest, unloaded/un-installed the
plugin and modified your vanilla enderchest. Then loaded the plugin up
again. In this case, the vanilla enderchest won't be migrated again as it
was already done the first time when your vanilla enderchest was empty.

If this is a testing server you're working on, try deleting your data.db if
you aren't using mysql and join the server again and you'll see that the
golder apples will be copied over.

Things to note are that you need to enable the enderchest conversion via
config and that migration only happens once when a player joins for the
first time. Hope thos helps :)

**Comment by ghost** [comment]
`joined the server woth an empty enderchest, unloaded/un-installed the plugin and modified your vanilla enderchest.`
I placed items in my vanilla enderchest before loading the plugin for the first time.
Even after deleting the SQLite file, the migration did not occur.

**Comment by minion325** [comment]
Did you set convert-current-ender-chest: true' before loading the plugin
after deleting the sqlite file?

**Comment by ghost** [comment]
Yes, I did.

**Comment by minion325** [comment]
Okay, will have a look into this and get back to you

**Comment by ichiru5555** [comment]
Which Java file is responsible for performing migrations from a vanilla Ender Chest? Sorry for the confusion.
